# Generated by Django 5.2.6 on 2025-09-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year_of_manufacture',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='product',
            name='year_of_product',
            field=models.IntegerField(default=2025),
        ),
    ]
