# Generated by Django 5.2.6 on 2025-09-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_year_of_manufacture_product_year_of_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey (Baju seragam)'), ('bola', 'Bola')], default='jersey', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=200000),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
